### ISSUE TITLE
Boxes look very large on some devices

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#10]
For this media query case the info boxes get very large, maybe they can be centered, with a max width / margin on the left and right of them?

![Screenshot_2020-08-17 Circles UBI Basic Income on the Blockchain(2)](https://user-images.githubusercontent.com/1822473/90632118-2d019580-e224-11ea-9162-9308918514dc.png)

**Comment by eminx** [comment]
Made an update. Please check @adzialocha ! 👍

**Comment by adzialocha** [comment]
Perfect, thank you @eminx!
