### ISSUE TITLE
Strange style glitches when loading page for the first time

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#11]
For some reason the styles do load async from the rest of the page which leads to a weird experience of the page glitching out in the first 1-3 seconds of loading time.

![photo_2020-08-19_14-02-36](https://user-images.githubusercontent.com/1822473/90632413-a8634700-e224-11ea-82f3-d0520983d97d.jpg)

**Comment by eminx** [comment]
This is actually a nextjs "feature" : to make it fast; the client loads and renders the html before it loads and applies the styling. It could be very useful, but I agree that with this nice design we have, it is pretty awkward. 

I'll look into it and see if it can be disabled!

**Comment by eminx** [comment]
This should be fixed now.

**Comment by adzialocha** [comment]
Feeling like a loading page now! :+1:  Thank you!
