### ISSUE TITLE
Focus border looks a little strange

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#12]
![photo_2020-08-19_14-07-20](https://user-images.githubusercontent.com/1822473/90632928-7999a080-e225-11ea-848d-fe1ae57873ec.jpg)

Sorry for the bad picture, I couldn't take a screenshot as the border would disappear then :-)

**Comment by eminx** [comment]
[Grommet](https://v2.grommet.io) has this focus thing to indicate any link/button clicked, which I think makes sense to have..? But styling-wise this is just default with the brand color of circles (some purple) and it can easily be changed. 

What do you find strange in this exactly @adzialocha ? How would you like it to be rather? :) Do you think the other focus styles for links are also strange?

**Comment by adzialocha** [comment]
The focus thing is great of course, I just wonder if there is something which is closer to the page design. My suggestion would be:

1. Use a less strong color (the purple is only used for the footer and call to action buttons)
2. Give more padding to the elements as the border really sits right at the edge which is a pattern I can't see anywhere else on the website
3. Make the borders more round? Again, this would suit the rest of the page better

... for the call-to-action button its alright (as it is purple and actually the border is round), for the social media icons its a little strange, but maybe there it can be the icon being colored black / purple and no border?

**Comment by adzialocha** [comment]
Also looking at the hamburger menu focus state I wonder if we can do something there as well, maybe again no border (similar to the social media icons mentioned above) but rather a different fill color?

**Comment by eminx** [comment]
Yes I agree, it could/should be different/better...
