### ISSUE TITLE
Social media buttons disappear to the right in floating menu

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#14]
![Screen Shot 2020-09-10 at 17 07 25](https://user-images.githubusercontent.com/1822473/92751860-ac4c3a00-f388-11ea-9dcc-a36f0018e151.png)

The forth icon in the social media box is disappearing behind the right window border.

**Comment by eminx** [comment]
Good you found out these stuff that appears only on large screens. I'd have no clue! Thanks @adzialocha !

Now this should be fixed.

**Comment by adzialocha** [comment]
@eminx Great! You can actually use the "Responsive Mode" in the Developer Browser Tools (Chrome or Firefox) to not only simulate mobile devices but also large desktop screens. So in case you're on a laptop, its very helpful for testing large screens :tada:

**Comment by eminx** [comment]
Indeed yes! I use the mobile views all the time but actually didn’t use the large ones. Glad for your tips 😊🙏🏼🌞
