### ISSUE TITLE
Optimize image size and format

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#18]
`4_Marketplace.svg` is > 1mb large, but I believe it will be replaced with another image, so maybe this does not matter for the final page? Also, is .svg the right format for such an image which is actually an embedded bitmap?

**Comment by eminx** [comment]
Totally! Now waiting for good, hires pngs from Swathi to update! <3

**Comment by eminx** [comment]
It’s changed to appropriately sized pings 👍🏽
