### ISSUE TITLE
Center subtitles

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#19]
"How it works", "Community" etc. seem not to be fully centered and looks a little strange (due to the `max-width` property), maybe centering them via `margin: 0 auto` helps?
![Screenshot_2020-09-14 Circles UBI Basic Income on the Blockchain](https://user-images.githubusercontent.com/1822473/93064285-a0f25a80-f677-11ea-8126-dbb7c4e3a652.png)

**Comment by eminx** [comment]
Should be fixed!
