### ISSUE TITLE
Could not restore account due to an unknow error

### ISSUE THREAD

**Issue by ligi** [CirclesUBI/circles-website#25]
Anyone knows what could be going here or how I could provide more context without revealing my seed words?

![Selection_265](https://user-images.githubusercontent.com/111600/98149511-9ca32a80-1ecd-11eb-9f84-22f71ac922c6.png)

**Comment by ligi** [comment]
Oh - this is getting a bit more serious I think: just created a new account (as I just wanted to try something out) - and I got the same seedwords again that just failed to restore - word for word.

**Comment by eminx** [comment]
@ligi This issue belongs to the wallet app (below), not the public website - which is this repo...

https://github.com/CirclesUBI/circles-myxogastria/issues
