### ISSUE TITLE
Add bussines section 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-website#49]
We need to add a new Tab/ section: Bussines.

_Design Material_ https://www.figma.com/file/cIO2cMtbZ8FVjUfNucKJCF/join.circles.net?node-id=3819%3A19830

LINKS:
_Embbeded video Link_ https://vimeo.com/469130953/06edd440b2

_FAQ button:_ https://joincircles.net/faq
_Handbook button:_ https://handbook.joincircles.net/
_Telegram button_ https://t.me/CirclesBazaar

**Comment by eminx** [comment]
@triaslucia Could you please tell me what these are, buttons or just visuals? If buttons, can you write the links pls. Thanks!

![Screenshot 2021-08-03 at 19 15 32](https://user-images.githubusercontent.com/22205310/128050308-679d882a-ea05-4634-baad-a87166b6b244.png)

**Comment by triaslucia** [comment]
This are drop-down buttons. If you click on them they will show the information , so no link needed. 
The frames are on the file already, also I constructed the fully open version so you can see distances. 

![Screenshot 2021-08-04 at 10 20 07 cleaned](https://user-images.githubusercontent.com/38475134/128147853-ed714423-dd50-4315-9c76-8e89cf8b1de3.png)

**Comment by triaslucia** [comment]
![Screenshot 2021-08-04 at 10 20 19 cleaned](https://user-images.githubusercontent.com/38475134/128147780-aa876730-63c7-41f5-9b96-70c15faa6b12.png)
