### ISSUE TITLE
FAQs screen  is Croped.

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-website#50]
The FAQ screen does not fit the screen. There are two white colums on each side. And the Social media icons are croped.

Browser: Mozilla, Safari, Chromium.

<img width="1677" alt="Screenshot 2021-08-04 at 20 11 56" src="https://user-images.githubusercontent.com/38475134/128235576-e22348d1-ca97-4d97-9a7e-42fad124730d.png">

**Comment by triaslucia** [comment]
Same with contact page: 

<img width="1675" alt="Screenshot 2021-08-05 at 09 59 35" src="https://user-images.githubusercontent.com/38475134/128405582-e9d2adfc-f2b2-4ee0-9daa-5a8a8fab3040.png">

**Comment by eminx** [comment]
These will be fixed with the businesses page launch: https://preview.joincircles.net
