### ISSUE TITLE
Erase the Donation information

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-website#55]
We can erase the Donation infomration from our landing page, as well as the button from the menu. 
Instead we will for now add a small text which is a description we are also using on the new communicational Material.

_Design Material_ https://www.figma.com/file/cIO2cMtbZ8FVjUfNucKJCF/join.circles.net?node-id=4079%3A6

**Comment by eminx** [comment]
Since it's such an important part of the website, we would want to have all translation before implementing this. 

AND I do believe it would be good to do it now ASAP with the businesses page launch. Could we please have the translation @triaslucia ?

**Comment by triaslucia** [comment]
_SPANISH_ 

Circles es una nueva forma de concebir el dinero. Circles es un sistema monetario impulsado por las personas. 
El intercambio con Circles se produce entre dos partes que se confían mutuamente  y  llegan a un acuerdo en un precio y cantidad proporcionada.
