### ISSUE TITLE
Heading logo cut on both sides

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#8]
![Screenshot_2020-08-17 Circles UBI Basic Income on the Blockchain](https://user-images.githubusercontent.com/1822473/90631806-ac429980-e223-11ea-981e-20b3c62cea60.png)

Firefox Version 79.0

**Comment by eminx** [comment]
The logo was cut by design that when one zooms out, it becomes like that.. 

Right now I just updated with a regular, non-cut logo. Please check with @swathi and let me know if this is the ideal solution @adzialocha 👍

**Comment by adzialocha** [comment]
Looking good to me now! Thanks!
