### ISSUE TITLE
Improve logo and hamburger positioning and size

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-website#9]
Minor nitpicks:

* The logo looks quite large in comparison to the hamburger menu (similar on mobile)
* The position of the hamburger to the window is much larger than on the logo

![Screenshot_2020-08-17 Circles UBI Basic Income on the Blockchain(1)](https://user-images.githubusercontent.com/1822473/90631991-f297f880-e223-11ea-82b5-e7fe3cd5a907.png)

Firefox Version 79.0

**Comment by eminx** [comment]
I just updated. Please check and let me know if this is cool! @adzialocha 

<img width="489" alt="Screenshot 2020-08-19 at 23 50 02" src="https://user-images.githubusercontent.com/22205310/90674433-c194e380-e276-11ea-9c58-d5021d493215.png">

**Comment by adzialocha** [comment]
Very nice!
